version: '3.8'
services:
  reactiveserver-cassandra-migration:
    environment:
      - CASSANDRA_CONTACT_POINT=reactiveserver-cassandra
      - USER=docker-cassandra-migration
      # - DEBUG_LOG=1 # uncomment to show debug logs during the migration process
      - CREATE_KEYSPACE_SCRIPT=create-keyspace.cql
    build:
      context: .
      dockerfile: cassandra/Cassandra-Migration.Dockerfile
    volumes:
      - ../resources/config/cql:/cql:ro
